name: Hello World
author: Tushar
description: Some desc

inputs:
  who-to-greet:
    description: 'who to greet'
    required: true
    default: tush

outputs:
  time:
    description: 'The greeting time'

runs:
  using: "docker"
  # image: "docker://dww:dss"
  image: "Dockerfile"
  args: 
    - ${{ inputs.who-to-greet }}