name: Test Hello Action
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: body
          assignees: 'tush-tr'
      - run: |
          echo ${{ steps.issue.outputs.issue}}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "Tushar"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
        
