on:
    pull_request:
        branches:
            - "main"
jobs:
    integration:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup nodejs
              uses: actions/setup-node@v1
              with:
                node-version: 14
            - run: npm ci
            - name: Check format
              run: npm run format:check